'use client'; // This layout uses client-side hooks and event listeners

// Include imports for Lenis AND the cursor
import React, { useEffect, useRef, useState } from 'react';
import Lenis from 'lenis';
import { motion, useMotionValue, useSpring } from "framer-motion";
import Image from "next/image";
import GooeyNav from "@/blocks/Components/GooeyNav/GooeyNav";
import { usePathname } from 'next/navigation';
// Import the Link component from next/link
import Link from 'next/link';
import dynamic from 'next/dynamic';

const Threads = dynamic(() => import("@/blocks/Backgrounds/Threads/Threads"), { ssr: false });
const Squares = dynamic(() => import("@/blocks/Backgrounds/Squares/Squares"), { ssr: false });


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { gilroy } from "@/fonts/fonts";

// Define items for GooeyNav (moved from page.tsx)
const items = [
  { label: "Home", href: "/" },
  { label: "Awards", href: "/Awards" },
  { label: "Projects", href: "/Projects" },
  { label: "Contact", href: "/Contact" },
];

// Define social media links and placeholder icon paths
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const socialLinks = [
  { platform: "GitHub", href: "https://github.com/Yuyuhiei", iconPath: "/icons/github_icon.svg" },
  { platform: "LinkedIn", href: "https://www.linkedin.com/in/charles-platon/", iconPath: "/icons/linkedin_icon.svg" },
  { platform: "Gmail", href: "mailto:charlesplaton@gmail.com", iconPath: "/icons/gmail_icon.svg" },
];


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // State for mobile menu (moved from page.tsx)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  // Theme state: 'dark' | 'light'
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  // Get current pathname
  const pathname = usePathname();

  // Calculate active index based on pathname
  const activeIndex = items.findIndex(item => item.href === pathname);

  // --- Theme Toggle ---
  useEffect(() => {
    const saved = localStorage.getItem('theme') as 'dark' | 'light' | null;
    if (saved) {
      setTheme(saved);
      if (saved === 'light') document.documentElement.classList.add('light');
    }
  }, []);

  const toggleTheme = () => {
    const next = theme === 'dark' ? 'light' : 'dark';
    setTheme(next);
    localStorage.setItem('theme', next);
    if (next === 'light') {
      document.documentElement.classList.add('light');
    } else {
      document.documentElement.classList.remove('light');
    }
  };
  // --- End Theme Toggle ---

  // --- Lenis Smooth Scrolling Implementation ---
  // Use useRef to hold the Lenis instance
  const lenis = useRef<Lenis | null>(null);

  useEffect(() => {
    // Initialize Lenis only in the browser environment
    if (typeof window !== 'undefined') {
      lenis.current = new Lenis({
        duration: 1.2, // Adjust the duration for scroll speed (seconds)
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // Easing function (default lenis easing)
        smoothWheel: true, // Enable smooth scrolling for mouse wheel
        // wheelMultiplier: 1, // Adjust scroll speed sensitivity
        // touchMultiplier: 1,
        // infinite: false, // Set to true for infinite looping scrolling
        // autoResize: true, // Automatically handle window resizing
      });

      // This function updates Lenis on each frame using requestAnimationFrame
      function raf(time: number) {
        lenis.current?.raf(time);
        requestAnimationFrame(raf);
      }

      // Start the animation loop
      requestAnimationFrame(raf);

      // Clean up the Lenis instance when the component unmounts
      return () => {
        lenis.current?.destroy();
      };
    }
  }, []); // Empty dependency array ensures this effect runs only once on mount and cleans up on unmount

  // --- Force scroll to top on page change ---
  useEffect(() => {
    if (lenis.current) {
      lenis.current.scrollTo(0, { immediate: true });
    }
    if (typeof window !== 'undefined') {
      window.scrollTo(0, 0);
    }
  }, [pathname]);
  // --- End Lenis Implementation ---


  // --- Custom Cursor Implementation (Moved from page.tsx) ---
  // Use MotionValues to track the raw mouse position
  // Initialize to 0 on both server and client to prevent hydration errors
  const cursorX = useMotionValue(0);
  const cursorY = useMotionValue(0);

  // Configure spring physics for the dot (follows closely)
  const dotSpringConfig = { damping: 25, stiffness: 200 };
  // Configure spring physics for the outline (trails the dot)
  const outlineSpringConfig = { damping: 35, stiffness: 400 }; // More damping/less stiffness for trailing

  // Create sprung motion values for the inner dot
  const dotX = useSpring(cursorX, dotSpringConfig);
  const dotY = useSpring(cursorY, dotSpringConfig);

  // Create sprung motion values for the outer outline, based on the dot's sprung values
  const outlineX = useSpring(dotX, outlineSpringConfig);
  const outlineY = useSpring(dotY, outlineSpringConfig);

  // Effect to update mouse position on mousemove AND set initial position after mount
  useEffect(() => {
    const moveCursor = (e: MouseEvent) => {
      cursorX.set(e.clientX);
      cursorY.set(e.clientY);
    };

    // Set initial cursor position to the center of the window after the component mounts
    // This runs only on the client after hydration
    // setTimeout is optional, but can help ensure initial positioning after paint
    setTimeout(() => {
      cursorX.set(window.innerWidth / 2);
      cursorY.set(window.innerHeight / 2);
    }, 0);


    // Add event listener for subsequent mouse movements
    window.addEventListener('mousemove', moveCursor);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('mousemove', moveCursor);
    };
  }, [cursorX, cursorY]); // Dependencies: update effect if motion values change (they won't here, but good practice)
  // --- End Custom Cursor Implementation ---


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // Added bg-black class for black background
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} antialiased font-gilroy bg-[var(--background)] text-[var(--foreground)] relative`}
        style={{ cursor: 'none' }} // Apply cursor: none globally to the body
      >
        {/* Global Persistent Background Animation */}
        {pathname !== '/Contact' ? (
          <>
            <div className="absolute top-[25vh] left-0 w-full h-[75vh] z-[-1] hidden md:block opacity-90 pointer-events-none">
              <Threads
                amplitude={2.5}
                distance={0}
                enableMouseInteraction={false}
              />
            </div>
            <div className="absolute top-[25vh] left-0 w-full h-[75vh] z-[-1] md:hidden opacity-40 pointer-events-none">
              <Threads
                amplitude={2.5}
                distance={0}
                enableMouseInteraction={false}
              />
            </div>
          </>
        ) : (
          <div
            className="fixed inset-0 z-[998] opacity-50 pointer-events-none"
            style={{ filter: "var(--squares-filter, none)" }}
          >
            <Squares
              speed={0.5}
              squareSize={50}
              direction="diagonal"
              borderColor="#fff"
              hoverFillColor="#222"
            />
          </div>
        )}

        {/* Custom Cursor Dot */}
        <motion.div
          style={{
            x: dotX, // Bind x position to the dot's sprung motion value
            y: dotY, // Bind y position to the dot's sprung motion value
            pointerEvents: 'none', // Ensure the cursor doesn't block clicks on elements below it
            left: 0, // Position relative to the viewport
            top: 0,
            position: 'fixed', // Stay in fixed position relative to the viewport
            zIndex: 9999, // Ensure it's always on top
            transform: 'translate(-50%, -50%)', // Center the div exactly on the cursor coordinates
            width: '8px', // Size of the inner dot
            height: '8px',
            borderRadius: '50%', // Make it round
            backgroundColor: '#06b6d4', // Cyan color (Tailwind cyan-500 equivalent)
            boxShadow: '0 0 10px 4px rgba(6, 182, 212, 0.7)', // Glowing effect
          }}
          className="hidden md:block" // Hide on mobile (optional, can be removed if you want it on mobile too)
        />
        {/* Custom Cursor Outline */}
        <motion.div
          style={{
            x: outlineX, // Bind x position to the outline's sprung motion value
            y: outlineY, // Bind y position to the outline's sprung motion value
            pointerEvents: 'none', // Ensure the cursor doesn't block clicks
            left: 0, // Position relative to the viewport
            top: 0,
            position: 'fixed', // Stay in fixed position
            zIndex: 9998, // Z-index slightly lower than the dot
            transform: 'translate(-50%, -50%)', // Center the div
            width: '30px', // Size of the outer circle
            height: '30px',
            borderRadius: '50%', // Make it round
            border: '2px solid #0891b2', // Border color (Tailwind cyan-600 equivalent)
            // Optional: opacity for transparency
            opacity: 0.5,
          }}
          className="hidden md:block" // Hide on mobile (optional, can be removed if you want it on mobile too)
        />
        {/* Header Section */}
        {/* Adjusted padding for different screen sizes */}
        <header className={`sticky top-0 flex w-full items-center justify-between px-4 py-2 md:px-8 md:py-3 bg-transparent backdrop-blur-[3px] ${pathname === '/Contact' ? 'z-[999]' : 'z-50'}`}>
          {/* Logo */}
          {/* Using Link for Logo if it navigates to home */}
          {/* Adjusted margin for different screen sizes */}
          <Link href="/" passHref>
            <Image
              src="/logo/cp-logo.svg"
              alt="CP Logo"
              width={35}
              height={35}
              className={`m-4 md:m-10 transition-all duration-300 hover:scale-150 hover:rotate-10 hover:brightness-125 ${theme === 'light' ? 'invert' : ''}`}
            />
          </Link>


          {/* Desktop Navigation + Theme Toggle inline */}
          <div className="hidden md:flex items-center">
            <div className="font-medium" style={{ height: '70px', width: '570px', position: 'relative' }}>
              <GooeyNav
                items={items}
                particleCount={15}
                particleDistances={[90, 10]}
                particleR={100}
                initialActiveIndex={activeIndex !== -1 ? activeIndex : 0}
                animationTime={600}
                timeVariance={300}
                colors={[1, 2, 3, 1, 2, 3, 1, 4]}
                theme={theme}
                onToggleTheme={toggleTheme}
              />
            </div>
          </div>

          {/* Hamburger button - visible only on small screens */}
          <button
            className="md:hidden text-white p-2 focus:outline-none"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle mobile menu" // Added accessibility label
          >
            {/* Hamburger icon lines */}
            {/* Added transition for animation if you want to animate the icon */}
            <div className="w-6 h-0.5 bg-white mb-1.5 transition-all duration-300 ease-in-out"></div>
            <div className="w-6 h-0.5 bg-white mb-1.5 transition-all duration-300 ease-in-out"></div>
            <div className="w-6 h-0.5 bg-white transition-all duration-300 ease-in-out"></div>
          </button>
        </header>

        {/* Mobile menu - only visible when mobileMenuOpen is true */}
        {/* Positioned fixed below the header, covers full width on mobile */}
        {mobileMenuOpen && (
          // Changed position from absolute to fixed
          // Adjusted top position to match header height at different breakpoints
          // Added overflow-y-auto to allow scrolling if the menu content is taller than the viewport
          <div className="md:hidden bg-transparent backdrop-blur-[10px] pt-10 fixed top-[72px] sm:top-[80px] md:top-[96px] right-0 left-0 z-40 p-4 sm:p-5 overflow-y-auto h-[calc(100vh - 72px)] sm:h-[calc(100vh - 80px)] md:h-[calc(100vh - 96px)]"> {/* Adjusted top position, added overflow-y-auto and height */}
            <nav className="flex flex-col space-y-4">
              {items.map((item, index) => (
                // Using <Link> for navigation items
                <Link
                  key={index}
                  href={item.href}
                  // Added responsive padding to the links
                  className="text-white hover:text-gray-300 py-2 px-4 font-medium text-base sm:text-lg" // Adjusted text size
                  onClick={() => setMobileMenuOpen(false)} // Keep the click handler to close the menu
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        )}
        {/* End Header Section */}

        {children} {/* This is where your page content (like page.tsx) will be rendered */}



      </body>
    </html>
  );
}
